### ISSUE TITLE
ライブラリ名を決める

### ISSUE THREAD

**Issue by sh1ma** [geek-space-hq/disco#2]

**Comment by sh1ma** [comment]
僕の案

- waon(discord -> 不協和音 -> 和音 -> waon)
- discotheque (discoの正式名称)

**Comment by ikngtty** [comment]
waon じゃ不協和音の逆じゃんって思いがある

**Comment by sh1ma** [comment]
@ikngtty 確かにｗ

**Comment by Lazialize** [comment]
light(or lite)cord

**Comment by sh1ma** [comment]
プロトタイプの名前は`discore`にしときます (discordのpythonチャンネルで)2票入ったので
